/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrganizationsIdRouteImport } from './routes/organizations/$id'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminRawPostsRouteImport } from './routes/admin/raw-posts'
import { Route as AdminQueueRouteImport } from './routes/admin/queue'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as authAdminloginRouteImport } from './routes/(auth)/adminlogin'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRawPostsRoute = AdminRawPostsRouteImport.update({
  id: '/raw-posts',
  path: '/raw-posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authAdminloginRoute = authAdminloginRouteImport.update({
  id: '/(auth)/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/adminlogin': typeof authAdminloginRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/raw-posts': typeof AdminRawPostsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/adminlogin': typeof authAdminloginRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/raw-posts': typeof AdminRawPostsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/admin': typeof AdminIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/(auth)/adminlogin': typeof authAdminloginRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/raw-posts': typeof AdminRawPostsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/faq'
    | '/adminlogin'
    | '/admin/events'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/queue'
    | '/admin/raw-posts'
    | '/admin/statistics'
    | '/organizations/$id'
    | '/admin/'
    | '/organizations'
    | '/api/auth/$'
    | '/api/images/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/faq'
    | '/adminlogin'
    | '/admin/events'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/queue'
    | '/admin/raw-posts'
    | '/admin/statistics'
    | '/organizations/$id'
    | '/admin'
    | '/organizations'
    | '/api/auth/$'
    | '/api/images/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/faq'
    | '/(auth)/adminlogin'
    | '/admin/events'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/queue'
    | '/admin/raw-posts'
    | '/admin/statistics'
    | '/organizations/$id'
    | '/admin/'
    | '/organizations/'
    | '/api/auth/$'
    | '/api/images/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  authAdminloginRoute: typeof authAdminloginRoute
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/raw-posts': {
      id: '/admin/raw-posts'
      path: '/raw-posts'
      fullPath: '/admin/raw-posts'
      preLoaderRoute: typeof AdminRawPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/adminlogin': {
      id: '/(auth)/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof authAdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminRawPostsRoute: typeof AdminRawPostsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminRawPostsRoute: AdminRawPostsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  authAdminloginRoute: authAdminloginRoute,
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
